In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
directory = "./Logs/"
save_path = "./Saved/"

from load_logs import *
from evaluation import *
from features import *
from visualize import *

logs, log_labels = read_logs_and_labels("./Saved/logs.txt", "./Saved/labels.txt")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import re
import os
import pickle
import sys
import random

from sklearn.cluster import DBSCAN
from sklearn import metrics
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cluster import KMeans


In [3]:
## Get labels & form into a matrix - for now starting with K means and DBScan

In [4]:
## Sort through labels where consensus becomes result - What to do if all results differ ?

In [5]:
##Bigram

In [9]:
labels_ = log_labels
            
X = get_features(logs, 2, 70)
X = X.toarray()

idxs = np.where(np.all(X == 0, axis=1))

X = np.delete(X, idxs, axis=0)
labels_ = np.delete(labels_, idxs)
## K Means Labels
kmeans = KMeans(init="k-means++", n_clusters=10,random_state=0).fit(X)
kLabels = kmeans.labels_

## DBSCAN Labels
model = DBSCAN(eps=0.4,min_samples=200,algorithm="auto",metric="cosine")
model.fit(X)
dbLabels = model.labels_

In [11]:
print(kLabels)
print(dbLabels)
labelsMatrix = []
labelsMatrix.append(kLabels)
labelsMatrix.append(dbLabels)
print(kLabels,dbLabels)

[5 4 4 ... 8 0 7]
[ 0  1  2 ... -1  3  3]
[5 4 4 ... 8 0 7] [ 0  1  2 ... -1  3  3]


In [5]:
##Trigram